# -*- coding: utf8 -*-

class ID:

    DISCONNECT = 0x84
    LOGIN = 0x8f
    PLAY_STATUS = 0x90
    BATCH = 0x92
    TEXT = 0x93
    SET_TIME = 0x94
    START_GAME = 0x95
    ADD_PLAYER2 = 0x96
    REMOVE_PLAYER = 0x97
    ADD_ENTITY = 0x98
    REMOVE_ENTITY = 0x99
    ADD_ITEM_ENTITY = 0x9a
    TAKE_ITEM_ENTITY = 0x9b
    MOVE_ENTITY = 0x9c
    MOVE_PLAYER = 0x9d
    REMOVE_BLOCK = 0x9e
    UPDATE_BLOCK = 0x9f
    ADD_PAINTING = 0xf0  # not support
    EXPLODE = 0xf1  # not support
    LEVEL_EVENT = 0xa2
    TILE_EVENT = 0xa3
    ENTITY_EVENT = 0xa4
    MOB_EFFECT = 0xf2  # not support
    UNKNOWN1 = 0xa6  # not support
    PLAYER_EQUIPMENT = 0xa7
    UNKNOWN3 = 0xa8  # not support
    PLAYER_ARMOR_EQUIPMENT = 0xf3  # not support
    INTERACT = 0xa9
    USE_ITEM = 0xaa
    PLAYER_ACTION = 0xab
    UNKNOWN4 = 0xac  # not support
    HURT_ARMOR = 0xf4  # not support
    SET_ENTITY_DATA = 0xad
    SET_ENTITY_MOTION = 0xae
    SET_ENTITY_LINK = 0xf5  # not support
    SET_HEALTH = 0xb0
    SET_SPAWN_POSITION = 0xb1
    ANIMATE = 0xb2
    RESPAWN = 0xb3
    UNKNOWN2 = 0xb4  # not support
    DROP_ITEM = 0xf6  # not support
    CONTAINER_OPEN = 0xb5
    CONTAINER_CLOSE = 0xb6
    CONTAINER_SET_SLOT = 0xb7
    CONTAINER_SET_DATA = 0xb8
    CONTAINER_SET_CONTENT = 0xb9
    RECIPE_DATA = 0xba
    MAKE_ITEM = 0xbb
    #CONTAINER_ACK = 0xf7
    ADVENTURE_SETTINGS = 0xbc
    TILE_ENTITY_DATA = 0xbd
    #PLAYER_INPUT = 0xf8
    FULL_CHUNK_DATA = 0xbf
    SET_DIFFICULTY = 0xc0
    ADD_PLAYER = 0xc3
